# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyDrone.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(640, 480)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		MainWindow.setMinimumSize(QtCore.QSize(640, 480))
		MainWindow.setMaximumSize(QtCore.QSize(640, 480))
		font = QtGui.QFont()
		font.setFamily("Roboto")
		MainWindow.setFont(font)
		MainWindow.setAutoFillBackground(False)
		MainWindow.setDocumentMode(False)
		MainWindow.setUnifiedTitleAndToolBarOnMac(False)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
		self.centralwidget.setObjectName("centralwidget")
		self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 431))
		self.gridLayoutWidget.setObjectName("gridLayoutWidget")
		self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
		self.gridLayout.setContentsMargins(0, 0, 0, 0)
		self.gridLayout.setObjectName("gridLayout")
		self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
		self.tabWidget.setSizePolicy(sizePolicy)
		self.tabWidget.setMinimumSize(QtCore.QSize(639, 0))
		self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.tabWidget.setAutoFillBackground(False)
		self.tabWidget.setObjectName("tabWidget")
		self.tabWidgetPage3 = QtWidgets.QWidget()
		self.tabWidgetPage3.setObjectName("tabWidgetPage3")
		self.ThrustverticalSlider = QtWidgets.QSlider(self.tabWidgetPage3)
		self.ThrustverticalSlider.setGeometry(QtCore.QRect(70, 110, 20, 160))
		self.ThrustverticalSlider.setMaximum(100)
		self.ThrustverticalSlider.setOrientation(QtCore.Qt.Vertical)
		self.ThrustverticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
		self.ThrustverticalSlider.setTickInterval(10)
		self.ThrustverticalSlider.setObjectName("ThrustverticalSlider")
		self.label = QtWidgets.QLabel(self.tabWidgetPage3)
		self.label.setGeometry(QtCore.QRect(55, 80, 50, 20))
		self.label.setObjectName("label")
		self.ThrustlcdNumber = QtWidgets.QLCDNumber(self.tabWidgetPage3)
		self.ThrustlcdNumber.setGeometry(QtCore.QRect(55, 280, 64, 23))
		self.ThrustlcdNumber.setFrameShape(QtWidgets.QFrame.Box)
		self.ThrustlcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
		self.ThrustlcdNumber.setLineWidth(1)
		self.ThrustlcdNumber.setSmallDecimalPoint(False)
		self.ThrustlcdNumber.setDigitCount(3)
		self.ThrustlcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.ThrustlcdNumber.setProperty("intValue", 0)
		self.ThrustlcdNumber.setObjectName("ThrustlcdNumber")
		self.AbortpushButton = QtWidgets.QPushButton(self.tabWidgetPage3)
		self.AbortpushButton.setGeometry(QtCore.QRect(320, 90, 291, 171))
		self.AbortpushButton.setCheckable(False)
		self.AbortpushButton.setAutoDefault(False)
		self.AbortpushButton.setDefault(False)
		self.AbortpushButton.setFlat(False)
		self.AbortpushButton.setObjectName("AbortpushButton")
		self.ArmpushButton = QtWidgets.QPushButton(self.tabWidgetPage3)
		self.ArmpushButton.setGeometry(QtCore.QRect(160, 90, 100, 27))
		self.ArmpushButton.setObjectName("ArmpushButton")
		self.tabWidget.addTab(self.tabWidgetPage3, "")
		self.tabWidgetPage1 = QtWidgets.QWidget()
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.tabWidgetPage1.sizePolicy().hasHeightForWidth())
		self.tabWidgetPage1.setSizePolicy(sizePolicy)
		self.tabWidgetPage1.setObjectName("tabWidgetPage1")
		self.ChatInput = QtWidgets.QLineEdit(self.tabWidgetPage1)
		self.ChatInput.setGeometry(QtCore.QRect(90, 290, 181, 25))
		self.ChatInput.setObjectName("ChatInput")
		self.ChatText = QtWidgets.QLabel(self.tabWidgetPage1)
		self.ChatText.setGeometry(QtCore.QRect(10, 290, 67, 17))
		self.ChatText.setObjectName("ChatText")
		self.Chat = QtWidgets.QTextBrowser(self.tabWidgetPage1)
		self.Chat.setGeometry(QtCore.QRect(80, 20, 501, 181))
		self.Chat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
		self.Chat.setReadOnly(True)
		self.Chat.setPlaceholderText("")
		self.Chat.setObjectName("Chat")
		self.ConnectButton = QtWidgets.QPushButton(self.tabWidgetPage1)
		self.ConnectButton.setGeometry(QtCore.QRect(500, 290, 100, 27))
		self.ConnectButton.setFlat(False)
		self.ConnectButton.setObjectName("ConnectButton")
		self.ServerInput = QtWidgets.QLineEdit(self.tabWidgetPage1)
		self.ServerInput.setGeometry(QtCore.QRect(309, 290, 181, 27))
		self.ServerInput.setInputMask("")
		self.ServerInput.setText("")
		self.ServerInput.setObjectName("ServerInput")
		self.tabWidget.addTab(self.tabWidgetPage1, "")
		self.tabWidgetPage2 = QtWidgets.QWidget()
		self.tabWidgetPage2.setObjectName("tabWidgetPage2")
		self.elevation_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.elevation_label.setGeometry(QtCore.QRect(30, 40, 91, 31))
		self.elevation_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.elevation_label.setAlignment(QtCore.Qt.AlignCenter)
		self.elevation_label.setObjectName("elevation_label")
		self.height_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.height_label.setGeometry(QtCore.QRect(30, 110, 91, 31))
		self.height_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.height_label.setAlignment(QtCore.Qt.AlignCenter)
		self.height_label.setObjectName("height_label")
		self.lcdNumber_elevation = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_elevation.setGeometry(QtCore.QRect(150, 45, 64, 23))
		self.lcdNumber_elevation.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_elevation.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_elevation.setObjectName("lcdNumber_elevation")
		self.lcdNumber_height = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_height.setGeometry(QtCore.QRect(150, 115, 64, 23))
		self.lcdNumber_height.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_height.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_height.setObjectName("lcdNumber_height")
		self.speed_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.speed_label.setGeometry(QtCore.QRect(30, 210, 91, 31))
		self.speed_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.speed_label.setAlignment(QtCore.Qt.AlignCenter)
		self.speed_label.setObjectName("speed_label")
		self.lcdNumber_speed = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_speed.setGeometry(QtCore.QRect(150, 215, 64, 23))
		self.lcdNumber_speed.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_speed.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_speed.setObjectName("lcdNumber_speed")
		self.gyro_y_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.gyro_y_label.setGeometry(QtCore.QRect(300, 40, 91, 31))
		self.gyro_y_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.gyro_y_label.setAlignment(QtCore.Qt.AlignCenter)
		self.gyro_y_label.setObjectName("gyro_y_label")
		self.lcdNumber_gyro_y = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_gyro_y.setGeometry(QtCore.QRect(420, 45, 64, 23))
		self.lcdNumber_gyro_y.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_gyro_y.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_gyro_y.setObjectName("lcdNumber_gyro_y")
		self.gyro_z_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.gyro_z_label.setGeometry(QtCore.QRect(300, 80, 91, 31))
		self.gyro_z_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.gyro_z_label.setAlignment(QtCore.Qt.AlignCenter)
		self.gyro_z_label.setObjectName("gyro_z_label")
		self.accel_x_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.accel_x_label.setGeometry(QtCore.QRect(300, 120, 91, 31))
		self.accel_x_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.accel_x_label.setAlignment(QtCore.Qt.AlignCenter)
		self.accel_x_label.setObjectName("accel_x_label")
		self.accel_y_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.accel_y_label.setGeometry(QtCore.QRect(300, 160, 91, 31))
		self.accel_y_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.accel_y_label.setAlignment(QtCore.Qt.AlignCenter)
		self.accel_y_label.setObjectName("accel_y_label")
		self.accel_z_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.accel_z_label.setGeometry(QtCore.QRect(300, 200, 91, 31))
		self.accel_z_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.accel_z_label.setAlignment(QtCore.Qt.AlignCenter)
		self.accel_z_label.setObjectName("accel_z_label")
		self.mag_x_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.mag_x_label.setGeometry(QtCore.QRect(300, 240, 91, 31))
		self.mag_x_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.mag_x_label.setAlignment(QtCore.Qt.AlignCenter)
		self.mag_x_label.setObjectName("mag_x_label")
		self.mag_y_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.mag_y_label.setGeometry(QtCore.QRect(300, 280, 91, 31))
		self.mag_y_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.mag_y_label.setAlignment(QtCore.Qt.AlignCenter)
		self.mag_y_label.setObjectName("mag_y_label")
		self.mag_z_label = QtWidgets.QLabel(self.tabWidgetPage2)
		self.mag_z_label.setGeometry(QtCore.QRect(300, 320, 91, 31))
		self.mag_z_label.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.mag_z_label.setAlignment(QtCore.Qt.AlignCenter)
		self.mag_z_label.setObjectName("mag_z_label")
		self.gyro_x_label_9 = QtWidgets.QLabel(self.tabWidgetPage2)
		self.gyro_x_label_9.setGeometry(QtCore.QRect(300, 0, 91, 31))
		self.gyro_x_label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.gyro_x_label_9.setAlignment(QtCore.Qt.AlignCenter)
		self.gyro_x_label_9.setObjectName("gyro_x_label_9")
		self.lcdNumber_gyro_x = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_gyro_x.setGeometry(QtCore.QRect(420, 5, 64, 23))
		self.lcdNumber_gyro_x.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_gyro_x.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_gyro_x.setObjectName("lcdNumber_gyro_x")
		self.lcdNumber_gyro_z = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_gyro_z.setGeometry(QtCore.QRect(420, 85, 64, 23))
		self.lcdNumber_gyro_z.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_gyro_z.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_gyro_z.setObjectName("lcdNumber_gyro_z")
		self.lcdNumber_accel_x = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_accel_x.setGeometry(QtCore.QRect(420, 125, 64, 23))
		self.lcdNumber_accel_x.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_accel_x.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_accel_x.setObjectName("lcdNumber_accel_x")
		self.lcdNumber_accel_y = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_accel_y.setGeometry(QtCore.QRect(420, 165, 64, 23))
		self.lcdNumber_accel_y.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_accel_y.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_accel_y.setObjectName("lcdNumber_accel_y")
		self.lcdNumber_accel_z = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_accel_z.setGeometry(QtCore.QRect(420, 205, 64, 23))
		self.lcdNumber_accel_z.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_accel_z.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_accel_z.setObjectName("lcdNumber_accel_z")
		self.lcdNumber_mag_x = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_mag_x.setGeometry(QtCore.QRect(420, 245, 64, 23))
		self.lcdNumber_mag_x.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_mag_x.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_mag_x.setObjectName("lcdNumber_mag_x")
		self.lcdNumber_mag_y = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_mag_y.setGeometry(QtCore.QRect(420, 285, 64, 23))
		self.lcdNumber_mag_y.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_mag_y.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_mag_y.setObjectName("lcdNumber_mag_y")
		self.lcdNumber_mag_z = QtWidgets.QLCDNumber(self.tabWidgetPage2)
		self.lcdNumber_mag_z.setGeometry(QtCore.QRect(420, 325, 64, 23))
		self.lcdNumber_mag_z.setFrameShadow(QtWidgets.QFrame.Plain)
		self.lcdNumber_mag_z.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
		self.lcdNumber_mag_z.setProperty("intValue", 0)
		self.lcdNumber_mag_z.setObjectName("lcdNumber_mag_z")
		self.tabWidget.addTab(self.tabWidgetPage2, "")
		self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 27))
		self.menubar.setAutoFillBackground(False)
		self.menubar.setDefaultUp(False)
		self.menubar.setNativeMenuBar(True)
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "PyDrone Control 1.0"))
		self.label.setText(_translate("MainWindow", "Thrust"))
		self.AbortpushButton.setText(_translate("MainWindow", "ABORT"))
		self.ArmpushButton.setText(_translate("MainWindow", "Arm"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("MainWindow", "Control"))
		self.ChatText.setText(_translate("MainWindow", "You:"))
		self.ConnectButton.setText(_translate("MainWindow", "Connect"))
		self.ServerInput.setPlaceholderText(_translate("MainWindow", "127.0.0.1:1337"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Chat"))
		self.elevation_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.elevation_label.setText(_translate("MainWindow", "Elevation [m]"))
		self.height_label.setToolTip(_translate("MainWindow", "Height from the sea level in meters"))
		self.height_label.setText(_translate("MainWindow", "Height [m]"))
		self.speed_label.setToolTip(_translate("MainWindow", "Height from the sea level in meters"))
		self.speed_label.setText(_translate("MainWindow", "Speed [m/s]"))
		self.gyro_y_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.gyro_y_label.setText(_translate("MainWindow", "gyroy"))
		self.gyro_z_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.gyro_z_label.setText(_translate("MainWindow", "gyroz"))
		self.accel_x_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.accel_x_label.setText(_translate("MainWindow", "accelx"))
		self.accel_y_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.accel_y_label.setText(_translate("MainWindow", "accely"))
		self.accel_z_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.accel_z_label.setText(_translate("MainWindow", "accelz"))
		self.mag_x_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.mag_x_label.setText(_translate("MainWindow", "magx"))
		self.mag_y_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.mag_y_label.setText(_translate("MainWindow", "magy"))
		self.mag_z_label.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.mag_z_label.setText(_translate("MainWindow", "magz"))
		self.gyro_x_label_9.setToolTip(_translate("MainWindow", "Height from the ground in meters"))
		self.gyro_x_label_9.setText(_translate("MainWindow", "gyrox"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "Stats"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

